version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: presentation_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}       
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}                 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}     
    volumes:
      - mysql-data:/var/lib/mysql      

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: presentation_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_ROOT_NAME} 
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
    ports:
      - "8080:80"    
    depends_on:
      - mysql        

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: presentation_backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: presentation_angular
    restart: on-failure
    volumes:
      - ./frontend/dist:/app/dist/frontend/browser
    depends_on:
      - backend

  server:
    image: nginx
    container_name: presentation_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  mysql-data: