name: Build Backend & Frontend Images
on:
    push:
        branches:
            - main

jobs:
    build_images:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: danielfarag
                password: ${{ secrets.AUTH_TOKEN }}

            - name: Build Docker image
              run: docker build -t ghcr.io/danielfarag/project1-node:latest ./backend
          
            - name: Push Docker image to GitHub Container Registry
              run: docker push ghcr.io/danielfarag/project1-angular:latest ./frontend